### ISSUE TITLE
Improve the 'Tell a Joke' button 

### ISSUE THREAD

**Issue by akshatjain1004** [Chirantanbanik/Random_Joke_Generator-Community_Project#15]
Improve the button and make it match with the current UI.

**Comment by akshatjain1004** [comment]
@Chirantanbanik can I take this up?

**Comment by Chirantanbanik** [comment]
Sure go for it.

**Comment by akshatjain1004** [comment]
Thanks! Can you please assign it to me and add a label for hacktoberfest 2022? @Chirantanbanik

**Comment by SattyamSamania** [comment]
Hey @Chirantanbanik can I work on this issue if it is still open.
