### ISSUE TITLE
Contributions / Pull Request are Welcomed 

### ISSUE THREAD

**Issue by Chirantanbanik** [Chirantanbanik/Random_Joke_Generator-Community_Project#3]

**Comment by salted0dreams** [comment]
i want to work on this

**Comment by vaibhavi-roy** [comment]
I want to work on this issue @Chirantanbanik 
Please assign this work to me
Thank you

**Comment by Chirantanbanik** [comment]
Saled0dreams & vaibhavi-roy can you please brief about the features, bugs or what's the thing you want to work on in the project?

**Comment by PriyanshuRj** [comment]
Hey @Chirantanbanik the sun logo doesn't look like an actual sun more like a settings logo i want to replace it.

**Comment by vaibhavi-roy** [comment]
@Chirantanbanik I will change the color theme and add some designs to the project.

**Comment by vaibhavi-roy** [comment]
@Chirantanbanik I will also make changes in the background so that we feel like we are reading some really funny jokes.

**Comment by yogitha02** [comment]
@Chirantanbanik 
Since most people are comfortable reading jokes in their interested language,why not use Translator 
to convert the jokes into that language.

Please do assign me . I would be glad to finish this task
![image](https://user-images.githubusercontent.com/73719563/193395876-8fa4bbc9-b24b-42b9-89d0-b9521732ce48.png)

**Comment by Chirantanbanik** [comment]
Okay @PriyanshuRj & @vaibhavi-roy go for it and please share a gif or video of the changes you have made after done with it.

**Comment by vaibhavi-roy** [comment]
Ok sure
Thank you

**Comment by saiteja1290** [comment]
Hey @Chirantanbanik , The responsiveness of the website is not totally intact , If I view it on a Phone The White Container doesn't have margins. 
![Screenshot 2022-10-01 122757](https://user-images.githubusercontent.com/39546736/193397170-8cc296a5-47ba-4d74-87cd-6dacd72f1818.png)
I make solve this issue and maybe can make the fonts better , looking forward for you to assign this task to me . After solving margins it would look something like this . 
![image](https://user-images.githubusercontent.com/39546736/193397233-8851571d-8242-4334-8530-3bca8fcef77b.png)

**Comment by KanishkDadhich** [comment]
Hey @Chirantanbanik . I would like to work on some issues in this project under Hacktoberfest.
They are :- 
1. Adding a Joke Emoji to the Website.
2. Changing the Background color and color of the text "Random Joke generator" to yellow. (P.S- This also looks decent in the Dark mode)

Please Assign me these issues.

**Comment by Chirantanbanik** [comment]
@saiteja1290 sure you can start working on it.

**Comment by vaibhavi-roy** [comment]
https://user-images.githubusercontent.com/97877161/193399787-603d6bca-6909-4b06-8109-51d471d60962.mp4

Hey @Chirantanbanik please check out the changes made by me so that I can make pr.
Thank you

**Comment by Manish5121** [comment]
Hey @Chirantanbanik ,
I've worked on design of this project and also added Glassmorphism effect .
Also i changed colour-scheme of both light mode and dark mode 
Please check the changes and let me know about it so that i can push a pr

CHANGES MADE 
-light mode
![2022-10-01 (1)](https://user-images.githubusercontent.com/94914243/193400229-027d9a94-f4d5-4cda-8aec-ec842ef9f587.png)
-dark mode
![2022-10-01](https://user-images.githubusercontent.com/94914243/193400235-4d4d20bc-8123-4786-8c5a-d8cbe479629c.png)

**Comment by vaibhavi-roy** [comment]
@Chirantanbanik I have created PR
Please check it

**Comment by SaumyaBhushan** [comment]
@Chirantanbanik  I would Like to add some GitHub actions workflow to this project. Let me know if you want this.

**Comment by Chirantanbanik** [comment]
@SaumyaBhushan can you please brief what will be the benefit of this feature?

**Comment by SaumyaBhushan** [comment]
Almost all the open source projects have some workflows attached with their projects . It basically helps in automating tasks. Suppose you want to run some checks before merging pull requests . It can be done using workflows. suppose you want to welcome new contributors it can be done using workflow. There are many more uses

**Comment by Chirantanbanik** [comment]
That's great Saumya go ahead👍🏼

**Comment by minhaj-313** [comment]
I want to Contribute in this Project for Hacktoberfest, If you Have any Issue then you can suggest me. I want to give my best,
