### ISSUE TITLE
Adding Box, Text Shadows With Background Gradient And Animations.

### ISSUE THREAD

**Issue by code08-ind** [Chirantanbanik/Random_Joke_Generator-Community_Project#43]
Adding Box Shadow Along With Text Shadow, Also Animations Along With Background Gradient Can Be Added To Make It Look More Impressive.

**Comment by Omkar845** [comment]
Can I work on this issue??

**Comment by code08-ind** [comment]
I have created the issue @Omkar845. You need to create the new issue as maintainers will see the issue that the person created and will assign to him/her.
