### ISSUE TITLE
Improve Responsive Design

### ISSUE THREAD

**Issue by aliaquintero** [Chirantanbanik/Random_Joke_Generator-Community_Project#48]
Hi there! 
Looks like this website is not responsive and when in mobile view the design is inconsistent. I'd like to fix it and implement a mobile-first design.

**Comment by Chirantanbanik** [comment]
Yeah go ahead👍🏼

**Comment by aliaquintero** [comment]
Submitted #57 to fix this issue :)

**Comment by aliaquintero** [comment]
Hi @Chirantanbanik, I just submitted #65 since a PR was accepted to fix responsiveness but it was not uniform in color and resizing. If you could please take a look at my PR - it allows for mobile-first design. Thank you!
